[libraries]

flexmark = { module = "com.vladsch.flexmark:flexmark-all" }

kairo-datetime = { module = "com.highbeam.kairo:kairo-datetime" }
kairo-dependencyInjection = { module = "com.highbeam.kairo:kairo-dependency-injection" }
kairo-dependencyInjectionTesting = { module = "com.highbeam.kairo:kairo-dependency-injection-testing" }
kairo-logging = { module = "com.highbeam.kairo:kairo-logging" }
kairo-protectedString = { module = "com.highbeam.kairo:kairo-protected-string" }
kairo-reflect = { module = "com.highbeam.kairo:kairo-reflect" }
kairo-serialization = { module = "com.highbeam.kairo:kairo-serialization" }
kairo-testing = { module = "com.highbeam.kairo:kairo-testing" }
kairo-util = { module = "com.highbeam.kairo:kairo-util" }

ktorUtils = { module = "io.ktor:ktor-utils" }

langchain4j = { module = "dev.langchain4j:langchain4j-core" }
langchain4j-anthropic = { module = "dev.langchain4j:langchain4j-anthropic" }
langchain4j-googleAiGemini = { module = "dev.langchain4j:langchain4j-google-ai-gemini" }
langchain4j-openAi = { module = "dev.langchain4j:langchain4j-open-ai" }
